name: Deploy JS Lambdas
on:
  push:
    branches:
      - main

jobs:
  pipeline:
    name: Create CF Stack
    runs-on: ubuntu-latest
    outputs:
      processor_lambda_function_name: ${{ steps.deploy_cfstack.outputs.processor_lambda_function_name }}

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Run deploy
        id: deploy_cfstack
        shell: bash
        run: ./deploy/deploy-cf-stack.sh

  deploy_sqs_processor:
    name: Deploy Processor Switch Lambda function code
    runs-on: ubuntu-latest
    needs: [ pipeline ]
    env:
      DIRECTORY: .
      LAMBDA_FUNCTION_NAME: ${{ needs.pipeline.outputs.processor_lambda_function_name }}

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-2"

      - name: Run tests
        shell: bash
        run: npm run test

      - name: Push latest code
        shell: bash
        run: ./deploy/deploy-function-code.sh
